// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhaleSpottingBackend.Database;

#nullable disable

namespace WhaleSpottingBackend.Migrations
{
    [DbContext(typeof(WhaleSpottingDbContext))]
    [Migration("20250625125111_Lower_Case_Table")]
    partial class Lower_Case_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhaleSpottingBackend.Models.WhaleSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Conservation_Status")
                        .HasColumnType("text");

                    b.Property<string>("Food")
                        .HasColumnType("text");

                    b.Property<string>("Habitat")
                        .HasColumnType("text");

                    b.Property<string>("Latin_Name")
                        .HasColumnType("text");

                    b.Property<int>("Max_Age")
                        .HasColumnType("integer");

                    b.Property<double>("Max_Length_Meters")
                        .HasColumnType("double precision");

                    b.Property<double>("Max_Weight_Tons")
                        .HasColumnType("double precision");

                    b.Property<string>("Species")
                        .HasColumnType("text");

                    b.Property<string>("Species_Group")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("whalespecies");
                });
#pragma warning restore 612, 618
        }
    }
}
